# PersistentVolumeClaim é usado para solicitar armazenamento persistente para um pod.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi