# Secret é mais seguro, não aparece em alguns logs, e é recomendado para armazenar informações sensíveis, como senhas, chaves de API, etc. Ele é codificado em base64, o que não é uma forma de criptografia, mas ajuda a evitar que as informações sejam facilmente legíveis. Para criar um Secret, você pode usar o seguinte comando:
apiVersion: v1
data:
  JWT_SECRET: YzJWamNtVjBiMHAzZEZOMWNHVnlVMlZuZFhKdlVHRnlZVTltYVdOcGJtRkJjR2t4TWpNME5UWTNPRGs9
  SPRING_DATASOURCE_PASSWORD: Q2lrNsKjNzIx
kind: Secret
metadata:
  name: oficina-secret
