spring:
  application:
    name: oficina-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oficina_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Use 'update' apenas em dev. Em prod, use Flyway e mude para 'validate'
      ddl-auto: update
    show-sql: true # Mostra os SQLs no console para debugar
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:c2VjcmV0b0p3dFN1cGVyU2VndXJvUGFyYU9maWNpbmFBcGkxMjM0NTY3ODk=}
  expiration: 86400000
