apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: oficina-config
                key: SPRING_DATASOURCE_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oficina-secret
                key: SPRING_DATASOURCE_PASSWORD
          - name: POSTGRES_DB
            value: oficina_db
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
        resources: {}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
status: {}
